- platform: template
  lights:
    hue_plug_as_light:
      friendly_name: "Hue Plug"
      value_template: "{{ states('switch.signify_netherlands_b_v_lom007') == 'on' }}"
      availability_template: "{{ has_value('switch.signify_netherlands_b_v_lom007') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.signify_netherlands_b_v_lom007
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.signify_netherlands_b_v_lom007
          